### ISSUE TITLE
Steam Group Membership Perks

### ISSUE THREAD

**Issue by my3t** [TitanTF/TitanTF#47]
Since the Sep 17 TF2 update, multiple features have broke. Servers are failing to fetch a player's Steam group membership status from Steam.

**Comment by my3t** [comment]
Resolved.

**Comment by leeroytm** [comment]
Reports have been filed that this issue is not yet resolved.

**Comment by my3t** [comment]
There is no fix for this indefinitely. We have removed Steam group membership perks, and enabled for everyone by default.
